# Example only - do not commit real values. The live secret is created by install.sh.
apiVersion: v1
kind: Secret
metadata:
  name: plane-secrets
  namespace: plane
type: Opaque
stringData:
  POSTGRES_PASSWORD: "CHANGE_ME"
  SECRET_KEY: "CHANGE_ME"
  LIVE_SERVER_SECRET_KEY: "CHANGE_ME"
  RABBITMQ_PASSWORD: "CHANGE_ME"
  AWS_ACCESS_KEY_ID: "plane"
  AWS_SECRET_ACCESS_KEY: "CHANGE_ME"
  DATABASE_URL: "postgresql://plane:CHANGE_ME@plane-db:5432/plane"
  AMQP_URL: "amqp://plane:CHANGE_ME@plane-mq:5672/plane"
