apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plane
  namespace: plane
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
    - host: plane.algios.dev
      http:
        paths:
          - path: /discord
            pathType: Prefix
            backend:
              service:
                name: discord
                port:
                  number: 3200
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy
                port:
                  number: 80
  tls:
    - hosts:
        - plane.algios.dev
      secretName: plane-tls
